// Good-faith access gate for the locally-installed (Electron) app — not DRM.
// Every install, even fully local/offline-capable ones, must periodically
// check in with the hosted license server so the admin can grant/revoke
// access. The check runs here in the main process (not the renderer) and
// gates window creation, so patching the renderer alone can't bypass it.
//
// Token verification uses only the bundled PUBLIC key (license-public-key.pem,
// generated by backend/scripts/generate-license-keys.js) — the private
// signing key never leaves the hosted server.

const { app } = require('electron')
const fs = require('fs')
const path = require('path')
const jwt = require('jsonwebtoken')

const LICENSE_SERVER_URL = process.env.MANAGRAM_LICENSE_SERVER_URL || 'https://managram.uk'
const PUBLIC_KEY_PATH = path.join(__dirname, 'license-public-key.pem')

function getCachePath() {
  return path.join(app.getPath('userData'), 'license-cache.json')
}

function readCache() {
  try {
    return JSON.parse(fs.readFileSync(getCachePath(), 'utf8'))
  } catch {
    return null
  }
}

function writeCache(data) {
  fs.writeFileSync(getCachePath(), JSON.stringify(data), 'utf8')
}

function getPublicKey() {
  return fs.readFileSync(PUBLIC_KEY_PATH, 'utf8')
}

// Verifies a cached token's signature + expiry, and refuses it outright if
// the system clock now reads earlier than the last time we saw a valid
// check-in — a cheap guard against trivially rolling the clock back to keep
// an expired token looking valid forever.
function verifyCached(cache) {
  if (!cache?.token) return { state: 'none' }

  const now = Date.now()
  if (cache.lastVerifiedAt && now < cache.lastVerifiedAt) {
    return { state: 'clock_rollback' }
  }

  try {
    const claims = jwt.verify(cache.token, getPublicKey(), { algorithms: ['RS256'] })
    if (claims.override === 'force_deny') return { state: 'denied', claims }
    return { state: 'valid', claims }
  } catch (err) {
    if (err.name === 'TokenExpiredError') return { state: 'expired' }
    return { state: 'invalid' }
  }
}

function getStatus() {
  return verifyCached(readCache())
}

async function login(email, password) {
  const response = await fetch(`${LICENSE_SERVER_URL}/account/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password, client: 'electron' }),
  })
  const data = await response.json()
  if (!response.ok) throw new Error(data.error || 'Login failed')

  writeCache({ token: data.token, lastVerifiedAt: Date.now() })
  return verifyCached(readCache())
}

// Opportunistic online re-check (on launch, and every few hours while
// running). On success, refreshes the cached token (sliding expiry). If
// offline, silently keeps using whatever's cached until its grace window
// lapses — that's by design, not an error.
async function refresh() {
  const cache = readCache()
  if (!cache?.token) return getStatus()

  try {
    const response = await fetch(`${LICENSE_SERVER_URL}/account/refresh`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${cache.token}` },
      body: JSON.stringify({ client: 'electron' }),
    })
    if (response.status === 401 || response.status === 402) {
      // Explicit revoke/lapse from the server — lock immediately, don't
      // fall back to the (now stale) cached token's remaining exp.
      writeCache({ token: null, lastVerifiedAt: Date.now() })
      return { state: 'denied' }
    }
    if (!response.ok) return getStatus(); // network/server hiccup — fall back to cached state

    const data = await response.json()
    writeCache({ token: data.token, lastVerifiedAt: Date.now() })
    return verifyCached(readCache())
  } catch {
    // No network — use the cached token until its own exp/grace lapses.
    return getStatus()
  }
}

function logout() {
  writeCache({ token: null, lastVerifiedAt: Date.now() })
}

module.exports = { getStatus, login, refresh, logout }
